---
# tasks file for xvt-dotnetcore-dev
- name: Add apt-key for Microsoft signature key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install microsoft repo
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ubuntu_version_codename }}-prod {{ ubuntu_version_codename }} main'
    state: present

- name: Install dotnet
  apt:
    name: "dotnet-sdk-{{ dotnet_version }}"
    state: present

- name: Add apt-key for mono project
  apt_key:
    url: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Install mono repo
  apt_repository:
    repo: 'deb http://download.mono-project.com/repo/ubuntu {{ ubuntu_version_codename }} main'
    state: present

- name: Install mono
  apt:
    name: mono-devel
    state: present

- name: Install nuget
  apt:
    name: nuget
    state: present
