- name: Install packages-microsoft-prod.deb to setup lates repository
  apt:
    deb: "https://packages.microsoft.com/config/ubuntu/{{ ubuntu_version[ansible_distribution_release] }}/packages-microsoft-prod.deb"
    state: present

- name: Install dotnet
  apt:
    name: "dotnet-sdk-{{ dotnet_version }}"
    state: present
    update_cache: yes
    cache_valid_time: 0

- name: Add apt-key for mono project
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Install mono repo
  apt_repository:
    repo: 'deb http://download.mono-project.com/repo/ubuntu {{ ansible_distribution_release }} main'
    state: present

- name: Install mono
  apt:
    name: mono-devel
    state: present

- name: Install nuget
  apt:
    name: nuget
    state: present
